'use strict';Registry.require(["crcrc","helper","promise"],()=>{const m=Registry.get("helper"),u=Registry.get("crcrc").cr,h=Registry.get("crcrc").crc,N=Registry.get("promise"),d={};Registry.register("layout/default/tabview","7c765150",{create:(x,l,f,O)=>{const a=m.filter(x,/[0-9a-zA-Z]/g);x=!1;void 0==f&&(f={tv:"tv",tv_table:"tv_table",tr_tabs:"tr_tabs",tr_content:"tr_content",td_content:"td_content",td_tabs:"td_tabs",tv_tabs_fill:"tv_tabs_fill",tv_tabs_table:"tv_tabs_table",tv_tabs_align:"tv_tabs_align",
tv_contents:"tv_contents",tv_tab_selected:"tv_tab tv_selected",tv_tab_close:"tv_tab_close",tv_tab:"tv_tab",tv_content:"tv_content"});const A=h("div",f.tv,"main"+a),v=h("table",f.tv_table+" noborder","main_table"+a);v.inserted?x=!0:(d[a]={},d[a].g_entries={},d[a].g_selectedId=null);const B=h("tr",f.tr_tabs,"tabs"+l.id+a),C=h("td",f.td_tabs,"pages"+a),D=h("div",f.tv_tabs_fill,"tv_tabs_fill"+a),E=h("div",f.tv_tabs_table,"tv_tabs_table"+a),n=h("div",f.tv_tabs_align,"tv_tabs_align"+a),F=h("tr",f.tr_content,
"content"+l.id+a),G=h("td",f.td_content,"content"+a),z=h("div",f.tv_contents,"tv_content"+a),H=u("tfoot","tv_footer_t"+a),I=u("tr","tv_footer_tr"+a),J=u("td","tv_footer_td"+a);H.appendChild(I);I.appendChild(J);E.appendChild(n);D.appendChild(E);C.appendChild(D);B.appendChild(C);v.appendChild(B);G.appendChild(z);F.appendChild(G);v.appendChild(F);v.appendChild(H);A.appendChild(v);l.appendChild(A);const y=(a,d,b)=>{d?a.setAttribute("style",b?m.staticVars.visible_move:m.staticVars.visible):a.setAttribute("style",
b?m.staticVars.invisible_move:m.staticVars.invisible);a.setAttribute("vis",d.toString())},K=(c,e)=>{c=c.getId();d[a].g_entries[c]&&e!=d[a].g_entries[c].visible&&(d[a].g_entries[c].visible=e,y(d[a].g_entries[c].tab,e))},L=(a,d)=>{a&&y(a.content,d,!1)},P=c=>{const e=Object.keys(d[a].g_entries);for(let b,g=0;b=e[g];g++){const e=d[a].g_entries[b];if(e.tab.id==c.id)return e}return null},w=c=>{if(null===c)return null;const e=Object.keys(d[a].g_entries);for(let b,g=0;b=e[g];g++){const e=d[a].g_entries[b];
if(e.entry.getId()==c)return e.entry}return null},Q=c=>{if(c.getId()!=d[a].g_selectedId){var e=c.getId();d[a].g_selectedId&&L(d[a].g_entries[d[a].g_selectedId],!1);Object.keys(d[a].g_entries).forEach(b=>{b=d[a].g_entries[b];b.entry.getId()==e?b.visible?b.selected||(b.tab.setAttribute("class",f.tv_tab_selected),b&&y(b.content,!0,!1),b.selected=!0):console.log("tv: WARN: tab selected but not visible!"):b.selected&&(b.tab.setAttribute("class",f.tv_tab),b&&y(b.content,!1,!1),b.selected=!1)});d[a].g_selectedId=
e}},M=c=>{c.hide();c=c.getId();if(c=d[a].g_entries[c]){c.tab.parentNode.removeChild(c.tab);c.content.parentNode.removeChild(c.content);a:{c=c.tab;const e=Object.keys(d[a].g_entries);for(let b,g=0;b=e[g];g++)if(d[a].g_entries[b].tab.id==c.id){c=b;break a}c=null}c&&delete d[a].g_entries[c]}else console.log("tv: WARN: tab not part of tabview!")};l=null;x?l=d[a].tv:(l={getTabById:w,getSelectedTab:function(){return w(d[a].g_selectedId)},getAllTabs:function(){const a=$(n).find("div[tvid]");let d,b;const g=
[];a.each((c,e)=>{(d=$(a.get(c)).attr("tvid"))&&(b=w(d))&&g.push(b)});return g},getNextTab:function(c){const e=$(n).find("div[tvid]");let b;d[a].g_selectedId&&e.each((c,f)=>{b||$(f).attr("tvid")===d[a].g_selectedId&&(b=$(e.get(c+1)).attr("tvid"))});return w(b||e.first().attr("tvid"))},getPreviousTab:function(c){const e=$(n).find("div[tvid]");let b;d[a].g_selectedId&&e.each((c,f)=>{b||$(f).attr("tvid")===d[a].g_selectedId&&(b=$(e.get(c-1)).attr("tvid"))});return w(b||e.last().attr("tvid"))},removeTab:M,
appendTab:function(a,d,b,f,h){return this.insertTab(void 0,a,d,b,f,h)},insertTab:function(c,e,b,g,l,q){null===c&&(c=n.firstChild);var p="tab_"+e;const k=u("div",p,"content"+a);var r=void 0!==k.inserted&&1==k.inserted;const m=u("div",p,"head_text"+a);b.appendChild(m);q&&(p=h("div",f.tv_tab_close,p,"tv_close"+a,"tab_close"),p.inserted||p.addEventListener("click",()=>{q()}),b.appendChild(p));if(r){if(r=P(k))return r.entry;console.log("tv: WARN: old tab, but not in tabs collection!")}let t;r=a=>{""!=
a.target.className&&a.target.className==f.tv_tab_close||t.select()};k.setAttribute("tvid",e);k.addEventListener("click",r);b.addEventListener("click",r);k.setAttribute("name","tabview_tab"+a);k.setAttribute("class",f.tv_tab);k.appendChild(b);c?n.insertBefore(k,c):n.appendChild(k);g.setAttribute("name","tabview_content"+a);g.setAttribute("class",f.tv_content);z.appendChild(g);t={getId:function(){return e},isVisible:function(){return"true"==k.getAttribute("vis")},isSelected:function(){return d[a].g_selectedId==
this.getId()},isCloseable:function(){return!!q},modified:function(){return $(b).hasClass("modified")},remove:function(){M(this)},hide:function(){var b=this.getId(),c=b==d[a].g_selectedId;d[a].g_entries[b]?K(this,!1):console.log("tv: WARN: tab not part of tabview!");if(c){c=b=null;for(const e in d[a].g_entries)d[a].g_entries[e].visible&&(b=d[a].g_entries[e],c||b.closable||(c=b));O||b.closable||(b=c);b?b.entry.select():(d[a].g_selectedId=null,console.log("tv: WARN: selected tab set, but entry collection empty!"))}},
show:function(){{const b=this.getId();d[a].g_entries[b]?K(this,!0):console.log("tv: WARN: tab not part of tabview!")}},select:function(a){if(a||!t.isSelected())a=N(),l&&l(a.promise()),Q(this),a.resolve()},setHeading:function(a,c,d){const e=b.firstChild;if(c&&a.length>c){const b=Math.round(c/2);e.textContent=a.substr(0,b)+"..."+a.substr(b-c);e.title=d||a}else e.textContent=a},toggleClass:function(a,c){$(b,z).toggleClass(a,c)},close:function(){q&&q()}};d[a].g_entries[e]={entry:t,tab:k,content:g,closable:null!=
q};L(d[a].g_entries[e],!1);t.show();return t},setFooter:function(a){J.appendChild(a)}},d[a].tv=l);return l}})});
