'use strict';(t=>{const f=t.rea;if(void 0!==f.globals._content)console.warn('content: Stop here, cause a second Tampermonkey instance was detected!\nThis can be caused by using "document.write" at Userscripts.\nSee https://code.google.com/p/chromium/issues/detail?id=253388 for more information');else{f.globals._content=!0;var l;t.Registry=(()=>{const d={};let e=[];const b=()=>{e=e.filter(a=>{let b=!1;a.r.forEach(a=>{d[a]||(b=!0)});if(b)return!0;a.fn()})},c=(a,c,g)=>{d[a]=g;b()},a=a=>{a=d[a];return a instanceof
Function?a():a};return{register:c,registerRaw:c,get:a,getRaw:a,require:function(a,c){e.push({r:a,fn:c});b()}}})();var u=(()=>{const d=b=>({}).toString.apply(b).match(/\s([a-z|A-Z]+)/)[1],e=b=>{if("Object"==d(b)){const c=[];for(const a in b)b.hasOwnProperty(a)&&c.push(a+":"+e(b[a]));return"{"+c.join(",")+"}"}if("Array"==d(b)){const c=[];b.forEach(a=>{c.push(e(a))});return"["+c.join(",")+"]"}return void 0===b?"undefined":null===b?"null":"Function"==d(b)?b.toString():'"'+b.toString()+'"'};return{createUUID:function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,
b=>{const c=16*Math.random()|0;return("x"==b?c:c&3|8).toString(16)})},processQueue:function(b){let c;for(;c=b.shift();)c()},serialize:e,toType:d}})(),A=(()=>{const d={_content:!0,JSHINT:!0},e=/(webkitStorageInfo|webkitIDB.*|webkitIndexedDB|webkitOfflineAudioContext|webkitAudioContext|webkitURL|webkitSpeech.*|Bluetooth.*|MIDI.*|StorageManager)/;return()=>{const b={};let c,a;const p=Object.getOwnPropertyNames(window),m=((a,b)=>{for(;(a=Object.getPrototypeOf(a))&&a!==Object.prototype;)b=b.concat(Object.getOwnPropertyNames(a));
return b})(window,[]);c=0;for(a=null;a=m[c];c++)d[a]||e.exec(a)||(2<a.length&&"on"===a.substr(0,2)?b[a]={proto:!0,event:!0}:b[a]={proto:!0});c=0;for(a=null;a=p[c];c++)d[a]||b[a]||e.exec(a)||(2<a.length&&"on"===a.substr(0,2)?b[a]={window:!0,event:!0}:b[a]={window:!0});const g={addEventListener:{window:1},alert:{window:1},atob:{window:1},blur:{window:1},btoa:{window:1},clearInterval:{window:1},clearTimeout:{window:1},close:{window:1},confirm:{window:1},decodeURI:{window:1},decodeURIComponent:{window:1},
dispatchEvent:{window:1},encodeURI:{window:1},encodeURIComponent:{window:1},eval:{window:1},find:{window:1},focus:{window:1},getComputedStyle:{window:1},getSelection:{window:1},isFinite:{window:1},isNaN:{window:1},location:{window:1},open:{window:1},openDialog:{window:1},parseFloat:{window:1},parseInt:{window:1},postMessage:{window:1},print:{window:1},prompt:{window:1},removeEventListener:{window:1},resizeBy:{window:1},resizeTo:{window:1},scroll:{window:1},scrollBy:{window:1},scrollByLines:{window:1},
scrollByPages:{window:1},scrollTo:{window:1},setInterval:{window:1},setTimeout:{window:1},stop:{window:1}};Object.keys(g).forEach(a=>{b[a]||(b[a]=g[a])});return b}})(),h=u.createUUID(),v=window.self==window.top,y=0,w,k=(d=>{const e=(a,b)=>{const c=d.createEvent("MutationEvent");c.initMutationEvent(a,!1,!1,null,null,null,JSON.stringify(b),c.ADDITION);return c},b=(a,b)=>{let c;a&&(c=r[a])&&(c(b),delete r[a])};let c,a;var p;let m;var g=1,r={};return{init:function(g){m||(m=g);p="2P_"+m;a="2C_"+m;d.addEventListener.apply(d,
[a,a=>{const g=JSON.parse(a.attrName);"message.response"==g.m?b(g.r,g.a):c&&c(g,g.r?a=>{a=e(p,{m:"message.response",a,r:g.r});d.dispatchEvent.apply(d,[a])}:()=>{})},!1])},send:function(a,b,c){if(c){{const a=++g;r[g]=c;c=a}}else c=null;a=e(p,{m:a,a:b,r:c});d.dispatchEvent.apply(d,[a])},onMessage:{addListener:function(a){c=a}},cleanup:function(){d.removeEventListener.apply(d,[a,c,!1])}}})(document),z=(()=>{const d={};let e;const b=b=>{let a=[],c=[];var m={postMessage:function(a){k.send("port.message",
{response_id:b,value:a})},onMessage:{addListener:function(b){a.push(b)}},onDisconnect:{addListener:function(a){c.push(a)}},disconnect:function(){k.send("port.message",{response_id:b,disconnect:!0});m=c=a=null;delete d[b]}};d[b]={message:function(b){a&&a.forEach(a=>{a(b)})},disconnect:function(g){c&&c.forEach(a=>{a(g)});m=c=a=null;delete d[b]}};return m};return{message:function(c){let a;c.connect?e&&e(c.destination,b(c.response_id)):(a=d[c.response_id])?c.disconnect?a.disconnect():a.message(c.value):
l&&console.warn("ports: unkown id",c.response_id,c)},connect:function(c){const a=u.createUUID();k.send("port.message",{response_id:a,connect:!0,destination:c});return b(a)},onConnect:{addListener:function(b){e=b}}}})(),n=(()=>{let d,e;const b=[],c=[];let a=()=>{l&&console.log("content: detected DOMContentLoaded "+h);e=!0;window.removeEventListener("DOMContentLoaded",a,!1);a=null;u.processQueue(b)},f=()=>{l&&console.log("content: detected load "+h);d=e=!0;m.cleanup();u.processQueue(c)};window.addEventListener("DOMContentLoaded",
a,!1);window.addEventListener("load",f,!1);var m={registerDomListener:function(a){e||d?a():b.push(a)},registerPageListener:function(a){d?a():c.push(a)},forcedLoad:function(){d||e||!f||(l&&console.log("content: use forced load "+h),f(!0))},seen:(()=>{const a={};Object.defineProperties(a,{load:{get:function(){return d},enumerable:!0},DOMContentLoaded:{get:function(){return e},enumerable:!0}});return a})(),cleanup:function(){a&&(window.removeEventListener("DOMContentLoaded",a,!1),a=null);f&&(window.removeEventListener("load",
f,!1),f=null)}};return m})(),q=(()=>({init:function(d){f.page.eval("("+w.backup+')(window, document,"'+d+'",'+l+");\n")},cleanup:function(){k.send("cleanup")},next:function(d,e,b){const c={short_id:f.runtime.short_id};"inIncognitoContext isFirstPartyIsolation downloadMode enforce_strict_mode measure_scripts version external_connect statistics".split(" ").forEach(a=>{c[a]=d[a]});c.sandbox_allow_getters=!0;c.detect_constructors_by_keys=f.FEATURES.RUNTIME.DETECT_CONSTRUCTORS_BY_KEYS;l&&(n.seen.load?
console.log("content: Start ENV with page loaded "+h):n.seen.DOMContentLoaded?console.log("content: Start ENV with DOMContentLoaded "+h):console.log("content: Start ENV normally "+h));e=w.next(h,JSON.stringify(d.scripts),u.serialize(e),JSON.stringify(b),JSON.stringify(c),JSON.stringify({}),y,void 0,void 0,void 0,void 0,l,n.seen.load,n.seen.DOMContentLoaded,w.environment);k.send("next",{src:e})}}))(),x=(()=>{const d={registerMenuCommand:function(b){const c=f.extension.connect("registerMenuCommand");
c.onMessage.addListener(a=>{a.run&&null!==c&&b.postMessage("run")});c.onDisconnect.addListener(()=>{b.disconnect()});b.onMessage.addListener(a=>{if("register"===a.method){var b=a.name,d=a.uuid;a=a.accessKey;var g=[h,b,d].join("#");c.postMessage({method:"registerMenuCommand",name:b,uuid:d,menuId:g,accessKey:a})}});b.onDisconnect.addListener(()=>{c.disconnect()})},openInTab:function(b){const c=f.extension.connect("openInTab");c.onMessage.addListener(a=>{b.postMessage(a)});c.onDisconnect.addListener(()=>
{b.disconnect()});b.onMessage.addListener(a=>{if("openTab"==a.method){let b=a.url;a=a.options;if("boolean"===typeof a||void 0===a)a={loadInBackground:a};const d=void 0===a.active?void 0===a.loadInBackground?!1:!a.loadInBackground:a.active,g=void 0===a.insert?!0:a.insert;b&&0===b.search(/^\/\//)&&(b=location.protocol+b);c.postMessage({method:"openInTab",details:{url:b,options:{active:!!d,insert:!!g,incognito:!!a.incognito,setParent:!a.incognito&&!!a.setParent}}})}else void 0!==a.name?c.postMessage({name:a.name}):
a.close&&c.postMessage({close:!0})});b.onDisconnect.addListener(()=>{c.disconnect()})},download:function(b){const c=f.extension.connect("download");c.onMessage.addListener(a=>{b.postMessage(a)});c.onDisconnect.addListener(()=>{b.disconnect()});b.onMessage.addListener(a=>{a.cancel?c.postMessage({cancel:!0,id:h}):(a=a.details,a.url&&"/"===a.url[0]&&(a.url=location.origin+a.url),c.postMessage({method:"download",details:a,id:h}))});b.onDisconnect.addListener(()=>{c.disconnect()})},webRequest:function(b){const c=
f.extension.connect("webRequest");c.onMessage.addListener(a=>{b.postMessage(a)});c.onDisconnect.addListener(()=>{b.disconnect()});b.onMessage.addListener(a=>{c.postMessage({method:"webRequest",rules:a.rules,uuid:a.uuid})});b.onDisconnect.addListener(()=>{c.disconnect()})},xhr:function(b){const c=f.extension.connect("xhr");c.onMessage.addListener(a=>{b.postMessage(a)});c.onDisconnect.addListener(()=>{b.disconnect()});b.onMessage.addListener(a=>{c.postMessage(a)});b.onDisconnect.addListener(()=>{c.disconnect()})},
values:function(b){const c=f.extension.connect("values");c.onMessage.addListener(a=>{b.postMessage(a)});c.onDisconnect.addListener(()=>{b.disconnect()});b.onMessage.addListener(a=>{c.postMessage(a)});b.onDisconnect.addListener(()=>{c.disconnect()})}},e={setClipboard:function(b,c){const a=b.content;b=b.info;const d=typeof b;let e,g;"object"===d?(b.type&&(e=b.type),b.mimetype&&(g=b.mimetype)):"string"===d&&(e=b);const r=g||("html"==e?"text/html":"text/plain");if(f.FEATURES.RUNTIME.CLIPBOARD_API)f.extension.sendMessage({method:"clipboard",
mimetype:r,content:a},()=>c());else{const b=c=>{document.removeEventListener("copy",b,!0);c.stopImmediatePropagation();c.preventDefault();c.clipboardData.setData(r,a)};document.addEventListener("copy",b,!0);document.execCommand("copy");c()}},notification:function(b,c){b.method="notification";f.extension.sendMessage(b,c)},syntaxCheck:function(b,c){b.method="syntaxCheck";f.extension.sendMessage(b,c)},closeTab:function(b,c){f.extension.sendMessage({method:"closeTab",id:h},a=>{a.error&&console.warn(a.error);
c()})},focusTab:function(b,c){f.extension.sendMessage({method:"focusTab",id:h},a=>{a.error&&console.warn(a.error);c()})},addStyle:function(b,c){try{const a=document.createElement("style");a.textContent=b.css||"";b.id&&a.setAttribute("id",b.id);(document.head||document.body||document.documentElement||document).appendChild(a);c()}catch(a){console.warn("content: error adding style",a)}},tabs:function(b,c){b.method="tabs";f.extension.sendMessage(b,a=>{c(a.data)})},cookie:function(b,c){b.method="cookie";
f.extension.sendMessage(b,a=>{c(a.data)})},api:function(b){b.method="api";f.extension.sendMessage(b,()=>{})}};return{init:function(){},getApi:function(){const b={};[e,d].forEach(c=>{Object.keys(c).map(a=>{b["GM_"+a]=c[a]})});return b},processMessage:function(b,c,a){if(b=e[b])return b(c,a);a()},processConnect:function(b,c){if(b=d[b])return b(c)}}})();f.extension.onMessage.addListener((d,e,b)=>{d.id&&d.id!=h?console.warn("content: Not for me! "+h.substr(0,10)+"!="+d.id):"executeScript"==d.method?d.url&&
0!==window.location.href.search(d.url)?l&&console.log("exec: URL doesn't match",window.location,d):d.topframe&&!v?l&&console.log("exec: topframe doesn't match",window.self,d):k.send("executeScript",d):"onLoad"==d.method?(document.readyState&&"complete"!==document.readyState||n.forcedLoad(),b({})):v&&("loadUrl"==d.method?(window.location=d.url,b({})):"reload"==d.method?(window.location.reload(),b({})):"confirm"==d.method?window.setTimeout(()=>{const c=window.confirm(d.msg);b({confirm:c})},100):"showMsg"==
d.method?window.setTimeout(()=>{window.setTimeout(()=>{window.alert(d.msg)},1);b({})},100):"setForeignAttr"==d.method?(k.send(d.method,d),b({})):window.console.log("content: unknown method "+d.method))});z.onConnect.addListener((d,e)=>{x.processConnect(d,e)});k.onMessage.addListener((d,e)=>{if("document.write"==d.m){const b=document.documentElement;window.setTimeout(()=>{b!==document.documentElement&&k.init()},0)}else"port.message"==d.m?z.message(d.a):"csp"==d.m?f.page.eval('window["'+d.a.id+'"] = function() { '+
d.a.src+" };\n"):"external.message"==d.m?f.extension.sendMessage({method:"externalMessage",request:d.a},b=>{e(b)}):x.processMessage(d.m,d.a,e)});Registry.require(["page.js"],()=>{w=Registry.getRaw("page.js");let d=!1;const e=(a,b,c)=>{let e=1;const g=()=>{l&&console.debug('content: send "prepare" message');f.extension.sendMessage({method:"prepare",id:h,topframe:v,url:window.location.href},f=>{d||(f?(d=!0,f.contexters||f.scripts&&f.scripts.length||f.external_connect?(c&&c(),b(f)):(q.cleanup(),a())):
(l&&console.debug("content: _early_ execution, connection to bg failed -> retry!"),window.setTimeout(g,e),e*=2))})};f.content.onReady(g)},b=location.pathname+location.search,c="TM_"+f.runtime.short_id+window.btoa(b.length+b).substr(0,255).replace(/[#=\/]/g,"_"),a=()=>{let a;let b;try{b=document.cookie.split(";")}catch(B){return}for(a=0;a<b.length;a++){var d=b[a].substr(0,b[a].indexOf("="));var e=b[a].substr(b[a].indexOf("=")+1);d=d.replace(/^\s+|\s+$/g,"");if(0===d.indexOf(c)&&(document.cookie=d+
"=; expires=Thu, 01 Jan 1970 00:00:01 GMT;",d=window.decodeURIComponent(e),0===d.indexOf("blob:")&&(e=new XMLHttpRequest,e.open("GET",d,!1),e.send(null),200===e.status||0===e.status)))try{return JSON.parse(e.responseText)}catch(B){console.warn("content: unable to decode"+e.responseText)}}},p=document.contentType&&"text/html"!=document.contentType;((a,b,c)=>{p?window.setTimeout(()=>{a(b,c)},1):a(b,c)})((b,c)=>{l&&console.log("content: Started ("+h+", "+window.location.origin+window.location.pathname+
")",t.tm_info);let d;f.FEATURES.RUNTIME.FAST_EXEC_SUPPORT&&(d=a())||(d=t.tm_info)?(delete t.tm_info,d.contexters||d.scripts&&d.scripts.length||d.external_connect?(q.init(h),k.init(h),c(d,"sync")):b(),f.FEATURES.RUNTIME.FAST_EXEC_SUPPORT&&f.extension.sendMessage({method:"prepare",url:window.location.href,cleanup:!0},()=>{})):p?e(b,c,()=>{q.init(h);k.init(h)}):(q.init(h),k.init(h),e(b,c))},()=>{l&&console.log("content: disable event processing for "+h);n.cleanup();q.cleanup();k.cleanup()},(a,b)=>{y=
a.logLevel;l|=60<=y;n.registerDomListener(()=>{k.send("DOMContentLoaded")});n.registerPageListener(()=>{k.send("load")});l&&console.log("content: "+(b||"normal")+" start event processing for "+h+" ("+a.scripts.length+" to run)");x.init(a.scripts);q.next(a,x.getApi(),A());v||window.addEventListener("unload",()=>{f.extension.sendMessage({method:"unLoad",id:h,topframe:!1,url:window.location.href},()=>{});n.cleanup();q.cleanup();k.cleanup()},!1)})})}})(window);
