'use strict';Registry.require(["helper","i18n"],()=>{const g=Registry.get("helper"),p=Registry.get("i18n");let k;const l=function(){this.name=this.supportURL=this.updateURL=this.downloadURL=this.fileURL=this.icon64=this.icon=this.uuid=null;this.name_i18n={};this.description=this.homepage=this.namespace=this.version=null;this.description_i18n={};this.system=!1;this.enabled=!0;this.position=0;this.grant=[];this.requires=[];this.includes=[];this.matches=[];this.excludes=[];this.resources=[];this.connects=
[];this.blockers=[];this.lastModified=0;this.webRequest=this.version=null;this.sync={imported:!1};this.options={check_for_updates:!0,comment:null,compatopts_for_requires:!0,compat_wrappedjsobject:!1,compat_metadata:!1,compat_foreach:!1,compat_arrayleft:!1,compat_prototypes:!1,compat_uW_gmonkey:!1,compat_forvarin:!1,noframes:null,awareOfChrome:!1,run_at:null,override:{use_includes:[],orig_includes:[],merge_includes:!0,use_matches:[],orig_matches:[],merge_matches:!0,use_excludes:[],orig_excludes:[],
merge_excludes:!0,use_connects:[],merge_connects:!0,use_blockers:[],orig_run_at:null,orig_noframes:null}}},n={init:function(a){k=a},Script:l,processMetaHeader:function(a){const d={};a=a.replace(/\t/g,"    ");a=a.replace(/\r/g,"\n");a=a.replace(/\n\n+/g,"\n");a=a.replace(/[^|\n][ \t]+\/\//g,"//");let b,e;a.split("\n").forEach(a=>{b=a.replace(/^[\t\s]*\/\//gi,"").replace(/^[\t\s]*/gi,"").replace(/\s\s+/gi," ");g.each({"uso:hash":!1,version:!1},(c,a)=>{const f=new RegExp("^@"+a+"[\\t\\s]","i");c=c||
a;-1!=b.search(f)&&(e=b.replace(f,"").replace(/[ \b\r\n]/gi,"").trim(),""!==e&&(d[c]=d[c]||e))})});return d},processHeader:function(a){const d=new l;a=a.replace(/\t/g,"    ");a=a.replace(/\r/g,"\n");a=a.replace(/\n\n+/g,"\n");a=a.replace(/[^|\n][ \t]+\/\//g,"//");let b,e,f,c;a.split("\n").forEach(a=>{f=a.replace(/^[\t\s]*\/\//gi,"").replace(/^[\t\s]*/gi,"");e=f.replace(/\s\s+/gi," ");c=!1;g.each({name:!1,description:!1},(a,b)=>{a=a||b;const h=null!==d[a];if((b=e.match(new RegExp("^@"+b+"(\\[[a-zA-Z_\\-0-9]+\\]|:[a-zA-Z_\\-0-9]+|#[a-zA-Z_\\-0-9]+"+
(h?"| [a-zA-Z_\\-0-9]+":"")+")?[\\t\\s]+(.*)$")))&&3===b.length&&(c=b[2].replace(/[\r\n]/gi,"").trim(),void 0!==c&&""!==c))if(h){var f;a+="_i18n";b[1]&&(f=b[1].match("[a-zA-Z_\\-0-9]+"))&&f[0]&&(f=p.normalizeLocale(f[0]),d[a][f]=c)}else d[a]=c});g.each({version:!1,updateURL:!1,downloadURL:!1,supportURL:!1,homepage:!1,homepageURL:"homepage",website:"homepage",source:"homepage",uuid:!1},(a,b)=>{const h=new RegExp("^@"+b+"[\\t\\s]","i");a=a||b;-1!=e.search(h)&&(c=e.replace(h,"").replace(/[ \b\r\n]/gi,
"").trim(),""!==c&&(d[a]=d[a]||c))});g.each({icon:!1,iconURL:"icon",defaulticon:"icon",icon64:!1,iconURL64:"icon64"},(a,b)=>{const h=new RegExp("^@"+b+"[\\t\\s]","i");a=a||b;-1!=e.search(h)&&(c=e.replace(h,"").replace(/[\b\r\n]/gi,"").trim(),""!==c&&(d[a]=d[a]||c))});g.each({namespace:!1,author:!1,copyright:!1},(a,b)=>{const e=new RegExp("^@"+b+"[\\t\\s]","i");a=a||b;-1!=f.search(e)&&(c=f.replace(e,"").replace(/[\b\r\n]/gi,"").trim(),""!==c&&(d[a]=d[a]||c))});g.each({"run-at":"run_at"},(a,b)=>{const f=
new RegExp("^@"+b+"[\\t\\s]","i");a=a||b;-1!=e.search(f)&&(c=e.replace(f,"").replace(/[\r\n]/gi,"").trim(),""!==c&&(d.options[a]=d.options[a]||c))});const m=a=>a.trim().replace(/ /gi,"%20").replace(/[\b\r\n]/gi,"");g.each({include:"includes",match:"matches",exclude:"excludes",connect:"connects","connect-src":"connects",domain:"connects"},(a,b)=>{const f=new RegExp("^@"+b+"[\\t\\s]","i");a=a||b;-1!=e.search(f)&&(c=m(e.replace(f,"")).trim())&&d[a].push(c)});-1!=e.search(/^@require[\t\s]/)&&(c=m(e.replace(/^@require[\t\s]*/gi,
"")).trim())&&d.requires.push({url:c,loaded:!1,textContent:""});if(-1!=e.search(/^@resource[\t\s]/)&&(c=e.replace(/^@resource[\t\s]*/gi,"").trim(),b=c.split(" "),2<=b.length)){a=b.shift();const c=m(b.join(" "));""!==a&&c&&d.resources.push({name:a,url:c,loaded:!1})}-1!=e.search(/^@grant[\t\s]/)&&(c=e.replace(/^@grant/gi,"").replace(/[\b\r\n]/gi,"").trim())&&d.grant.push(c);g.each({noframes:!1,nocompat:"awareOfChrome"},(a,b)=>{a=a||b;-1!=e.search(new RegExp("^@"+b+"[\\t\\s\\r\\n]?"))&&(d.options[a]=
!0)});if(-1!=e.search(/^@webRequest[\t\s]/)&&(c=e.replace(/^@webRequest/gi,"").replace(/[\b\r\n]/gi,"").trim())){let a;try{a=JSON.parse(c),d.webRequest=(d.webRequest||[]).concat(a instanceof Array?a:[a])}catch(q){return console.warn("parser: unable to process webRequest header",c),new l}}});d.version||(d.version="0.0");return d},getHeaderTags:function(){return{start:"==UserScript==",stop:"==/UserScript=="}},getHeader:function(a){const d=g.getStringBetweenTags(a,"==UserScript==","==/UserScript==");
if(!d)return null;const b=a.search("==UserScript=="),e=a.search("<html>");a=a.search("<body>");return 0<e&&e<b||0<a&&a<b?null:d},createScriptFromSrc:function(a){a=(a||"").replace(/(\r\n|\n|\r)/gm,"\n");const d=n.getHeader(a);if(!d)return{};const b=n.processHeader(d);b.textContent=a;b.header=d;b.options.awareOfChrome||(b.options.compat_wrappedjsobject=a!=k.unWrappedJsObjectify(a),b.options.compat_metadata=a!=k.unMetaDataify(a),b.options.compat_prototypes=k.findPrototypes(a));-1!=a.search("unsafeWindow.gmonkey")&&
(b.options.compat_uW_gmonkey=!0);return b},versionCmp:(()=>{const a=a=>{a=a.split(".");return a.slice(0,3).concat([a.slice(3).join(".")]).concat([0,0,0,0]).slice(0,4).map(a=>{a=a.toString().match(/((?:\-?[0-9]+)?)([^0-9\-]*)((?:\-?[0-9]+)?)(.*)/);return[Number(a[1]),a[2],Number(a[3]),a[4]]}).reduce((a,b)=>a.concat(b))},d=(b,e)=>{b=Array.isArray(b)?b:a(b);e=Array.isArray(e)?e:a(e);for(let a=0;16>a;a++){var f=b[a],c=e[a];if(1===a%2){if(!f&&c)return d.eNEWER;if(f&&!c)return d.eOLDER;f=f.match(/\w/g)||
[];c=c.match(/\w/g)||[];for(let a=0;a<Math.min(f.length,c.length);a++){if(f[a].charCodeAt(0)>c[a].charCodeAt(0))return d.eNEWER;if(f[a].charCodeAt(0)<c[a].charCodeAt(0))return d.eOLDER}if(f.length>c.length)return d.eNEWER;if(f.length<c.length)return d.eOLDER}else{if(Number(f)>Number(c))return d.eNEWER;if(Number(f)<Number(c))return d.eOLDER}}return d.eEQUAL};d.__proto__.eERROR=-2;d.__proto__.eOLDER=-1;d.__proto__.eEQUAL=0;d.__proto__.eNEWER=1;return d})()};Registry.register("parser","7c765150",
n)});
