'use strict';Registry.require(["promise","helper","convert"],()=>{const h=Registry.get("promise"),t=Registry.get("helper"),k=Registry.get("convert");let u=()=>{const c=h();Registry.vendor(["vendor/jszip/jszip"],()=>{u=h.Pledge;c.resolve()});return c.promise()};const l=(()=>{let c,e=!1,g;const b=()=>{const a=h();return g=a};return{write:function(){const a=h();e=!1;c=new JSZip;a.resolve(c);return a.promise()},open:function(a){const d=b();e=!0;JSZip.loadAsync(a).then(a=>{c=a;d.resolve(c)},a=>{g&&g.reject(a);
d.reject(a)});return d.promise()},entries:function(){const a=b(),d=c.files;a.resolve(Object.keys(d).map(a=>{if((a=d[a])&&!a.dir)return{filename:a.name}}).filter(a=>a));return a.promise()},get:function(a){const d=b();c.file(a.filename).async("arraybuffer").then(a=>{d.resolve(a)});return d.promise()},put:function(a,d,f){const m=b();try{c.file(a,d,{date:f?new Date(f):void 0}),m.resolve()}catch(n){m.reject(n)}return m.promise()},end:function(){const a=b();e?a.resolve():c.generateAsync({type:"blob",compression:"DEFLATE",
comment:"Created by Tampermonkey"}).then(d=>{a.resolve(d)},d=>{a.reject(d)});return a.promise()}}})();Registry.register("porter","7c765150",{zip:{create:function(c,e){const g=h();let b=0;u().then(()=>l.write()).then(a=>{const d=h(),f={},m=(a,d)=>{let b=[a,d].join(".");if(f[b]){let p;do p=a+" ("+f[b]+")",b=[p,d].join("."),f[b]++;while(f[b]);return m(p,d)}f[b]=1;return b},e=c.length,r=()=>{if(!c.length)return d.resolve();const a=c.shift(),f=a.meta.name.replace(/[\\\/$*?|]/g,"-"),q=m(f,"user.js"),
w=m(f,"options.json"),n=m(f,"storage.json"),x=JSON.stringify({options:a.options,settings:a.settings,meta:a.meta}),v=a.storage?JSON.stringify(a.storage):null;b+=a.source.length;console.log("porter: add to zip",q,b);g.notify("Zip: "+Math.floor((e-c.length)/e*100)+"%");l.put(q,a.source,a.meta.modified).then(()=>{b+=x.length;console.log("porter: add to zip",w,b);return l.put(w,x)}).then(()=>{if(!v)return h.Pledge();b+=v.length;console.log("porter: add to zip",n,b);return l.put(n,v)}).then(()=>{if(!a.resources.length&&
!a.requires.length)return h.Pledge();const d=[];["resources","requires"].forEach(b=>{a[b].forEach((a,f)=>{if(void 0!==a.source){f=a.meta.name.replace(/[\\\/$*?|]/g,"-");var r=k.MD5(b+a.meta.url),c=[q,r,f].join("-"),p=JSON.stringify(a.meta);a=k.str2arrbuf(a.source,"resources"==b?void 0:"UTF-8");d.push(l.put(c,a).then(()=>l.put(c+"."+b+".json",p)))}})});return h.when(d)}).fail(a=>{console.log("porter: add to zip failed",a)}).always(()=>{console.log("porter: add to zip -> next round");window.setTimeout(r,
5)})};r();return d.promise()}).then(()=>{console.log("porter: add global props");return e?l.put("Tampermonkey.global.json",JSON.stringify(e)):h.Pledge()}).then(()=>l.end()).done(a=>{g.resolve(a)}).fail(()=>{g.reject()});return g.promise()},read:function(c){const e=h();let g;u().then(()=>l.open(c)).then(()=>l.entries()).then(b=>{const a=h(),d={},f={},c=b.length,n=()=>{if(b.length){const a=b.shift();console.log("porter: read from zip",a.filename);l.get(a).done(b=>{let c=a.filename.match(/((.*)\.(storage\.json)|(.*)\.(options\.json)|(.*)\.(global\.json)|(.*)\.(user\.js)|(.*)\.user\.js-[0-9a-f]+-.*\.(resources\.json)|(.*)\.user\.js-[0-9a-f]+-.*\.(requires\.json))$/);
c&&(c=c.slice(1).filter(a=>a));if(!c||3>c.length)f[a.filename]=b;else try{const f=c[1],e=c[2];d[f]=d[f]||{resources:{},requires:{}};b=k.arrbuf2str(b,"UTF-8");"global.json"==e?g=JSON.parse(b):"user.js"==e?d[f].source=b:"options.json"==e?d[f].options=JSON.parse(b):"resources.json"==e?d[f].resources[a.filename]={name:a.filename,data:JSON.parse(b)}:"requires.json"==e?d[f].requires[a.filename]={name:a.filename,data:JSON.parse(b)}:"storage.json"==e&&(d[f].storage=JSON.parse(b))}catch(q){console.warn("porter: read from zip failed",
q)}}).always(()=>{e.notify("Zip: "+Math.floor((c-b.length)/c*100)+"%");window.setTimeout(n,5)})}else{const b=[];t.each(d,(a,d)=>{const c=a.options||{};c.source=a.source;c.storage=a.storage;["resources","requires"].forEach(b=>{const d=a[b];d&&t.each(d,(a,d)=>{let e;d=a.name.replace("."+b+".json","");if(e=f[d])c[b]=d=c[b]||[],d.push({meta:a.data,source:k.arrbuf2str(e,"resources"==b?void 0:"UTF-8")})})});b.push(c)});a.resolve({scripts:b,global_settings:g})}};n();return a.promise()}).done(b=>{e.resolve(b)}).fail(()=>
{e.reject()});return e.promise()}},json:{create:function(c,e){const g=h(),b={created_by:"Tampermonkey",version:"1",scripts:[],settings:e};c.forEach(a=>{const d={name:a.meta.name,options:a.options,storage:a.storage,enabled:a.settings.enabled,position:a.settings.position,file_url:a.meta.file_url,uuid:a.meta.uuid,source:k.Base64.encode(k.UTF8.encode(a.source))};["resources","requires"].forEach(b=>{const c=a[b];if(c&&c.length){var f=d[b]=[];c.forEach((a,b)=>{void 0!==a.source&&(b=a.meta,a=k.Base64.encode(k.UTF8.encode(a.source)),
f.push({meta:b,source:a}))})}});b.scripts.push(d)});g.resolve(JSON.stringify(b));return g.promise()},read:function(c){const e=h(),g=b=>{if(b.trim()){var a=null;try{return a=JSON.parse(b),a.scripts=t.map(a.scripts,a=>{const b={meta:{uuid:a.uuid,name:a.name,file_url:a.file_url},settings:{enabled:a.enabled,position:a.position},options:a.options,storage:a.storage,source:k.UTF8.decode(k.Base64.decode(a.source))};["resources","requires"].forEach(d=>{const c=a[d];c&&c.length&&(b[d]=c.map(a=>({meta:a.meta,
source:k.UTF8.decode(k.Base64.decode(a.source))})))});return b}),e.resolve({scripts:a.scripts,global_settings:a.settings})}catch(d){if(-1!=b.search("<body>")){a=b.indexOf("<body>");const c=b.lastIndexOf("</body>");if(-1!=a&&-1!=c)return b=b.substr(a+6,c-(a+6)),g(b)}}}e.reject()};g(c);return e.promise()}}})});
