'use strict';Registry.require(["promise","uri","helper"],()=>{(g=>{const L=Registry.get("promise"),M=Registry.get("uri"),N=Registry.get("helper"),t=rea.FEATURES,n=t.HTML5.LOCALSTORAGE;let z,A;const u=(a,c)=>{a&&c&&Object.keys(c).forEach(b=>{a[b]=c[b]})},f=(a,c)=>{if("string"===typeof k)a="G";else{a=a||"default";a=k.enabled&&!1===k.enabled[a]?null:k.tracker[a]||k.tracker["default"];if(null===a)return;a=(a||k.tracker["default"]).match(/[0-9]*/g).join("").split("").map(b=>String.fromCharCode(b.charCodeAt(0)+
23)).join("")}return[a].concat(c?[c]:[]).join(".")},p=(a,c)=>{let b=100*Math.random()<c;if(n)try{let d,e;const h=["wsr",a,c].join("_"),q=Date.now();if(d=n.getItem(h)){try{e=JSON.parse(d)}catch(O){}if(!e||e.ts+864E7<q)e={ts:q,w:b}}else e={ts:q,w:b};b=e.w;n.setItem(h,JSON.stringify(e))}catch(d){}return b},v=()=>({enabled:["default",p("UA-40782729",10),"api",p("UA-40782729",.001)],options:[],tracker:"script UA-40782729-2 script_update UA-40782729-2 naverr UA-40782729-3 api UA-40782729-4 cloud UA-40782729-5 default UA-40782729-6".split(" ")}),
B=()=>({enabled:["default",!0,"api",p("UA-149349990",.001)],options:[],tracker:["default","UA-149349990-1"]}),C=()=>({enabled:["default",!0,"api",p("UA-152632898",5E-4)],options:[],tracker:["default","UA-152632898-1"]}),D=()=>"UA-40861355-1",E=()=>"UA-57518333-1",F=()=>({enabled:["default",!0,"api",p("UA-152641681",5E-4)],options:[],tracker:["default","UA-152641681-1"]}),G=()=>({options:[],tracker:["default","UA-83591358-1","api",null]}),w={"default":v,gcal:v,G3XV:B,saap:B,fire:C,firb:C,iikm:F,neuu:E,
jecn:E,dhdg:()=>({enabled:["default",p("UA-40861355",1),"api",p("UA-40861355",5E-4)],options:[],tracker:["script","UA-40861355-2","script_update","UA-40861355-3","error","UA-40861355-4","naverr","UA-40861355-5","default","UA-40861355-6","api","UA-40861355-7","cloud","UA-40861355-8","browser",null]}),dcgo:D,bnim:D,mfdh:v,gz80:F,heif:G,"5snx":G};var k=(a=>{let c=a();"string"===typeof c&&(c={tracker:["default",c]});let b;const d={options:{},tracker:{},enabled:{}};Object.keys(d).forEach(a=>{if(c[a])for(b=
0;b<c[a].length;b+=2)d[a][c[a][b]]=c[a][b+1]});return d})(w[rea.runtime.short_id]||w["default"]);const P=[{msg:"a disconnected port"},{msg:"Function.prototype.apply: Arguments list has wrong type",url:"event_bindings"},{msg:"Script error."}];let H=!1,I=!1,l=!1;g._gaq=g._gaq||[];let r=[];const J=()=>{console.log("statistics: Unable to load GA -> enable emergency mode");const a={},c=()=>{let a=n?n.getItem("ga_clientId"):N.createUUID();n&&n.setItem("ga_clientId",a);return a};g.ga=(b,d,e,h,q,g,f)=>{if("create"==
b)a[h.name]=d;else{b=b.split(".");let g,k,l;(g=b[0])&&(k=a[g])&&(l=b[1])&&"send"==l&&"object"!=typeof h&&(f={v:1,aip:1,t:d,dl:location.href,cid:c(),tid:k,ni:f&&f.nonInteraction?1:void 0,z:Date.now()},u(f,"event"==d?{ec:e,ea:h,el:q,ev:void 0}:{dp:e}),d="https://www.google-analytics.com/collect?"+M.hash2params(f),e=new XMLHttpRequest,e.onerror=a=>{console.log("statistics: sending data failed",a)},e.open("GET",d),e.send(null))}};g.ga.getByName=()=>({get:function(a){if("clientId"===a)return c()}})},Q=
()=>{const a=()=>{let a;for(;a=r.shift();)a();r=!1},c=()=>{J();a()};t.RUNTIME.FIREFOX||t.RUNTIME.SAFARI||z?(J(),a()):((b,d,e,h)=>{b.GoogleAnalyticsObject="ga";b.ga=b.ga||((...a)=>{(b.ga.q=b.ga.q||[]).push(a)});b.ga.l=1*new Date;e=d.createElement("script");h=d.getElementsByTagName("script")[0]||d.head;e.async=!0;e.src="https://ssl.google-analytics.com/analytics.js";e.addEventListener("load",a,!1);e.addEventListener("error",c,!1);h.parentNode.insertBefore(e,h)})(g,document)},m=(a,...c)=>{a&&R().done(()=>
{g.ga.apply(g,[a,...c])})},T=()=>{I||(r.push(()=>{const a=[],c={};Object.keys(k.tracker).forEach(b=>{const d=f(b);if(d&&!c[d]){c[d]=!0;var e={name:d};u(e,null);u(e,(k.options||{})[b]);a.push(["create",k.tracker[b],"auto",e]);a.push([d+".set","checkProtocolTask",null]);a.push([d+".set","anonymizeIp",!0]);a.push([d+".set","forceSSL",!0])}});a.forEach(a=>{g.ga.apply(g,a)});w[rea.runtime.short_id]||window.setTimeout(S,3E4)}),Q(),I=!0)};var K=a=>{H&&(l=a)&&(T(),A&&x&&(x(),x=void 0))},x=()=>{m(f("pageview",
"send"),"pageview",g.location.pathname||g.location.href)},S=()=>{l&&m(f("extension","send"),"event","Extension","ID",rea.runtime.id+" @ "+navigator.userAgent,null,{nonInteraction:!0})},y=(a,c,b)=>{if(l&&a.search){void 0===c&&(c="");void 0===b&&(c+=" "+window.location.href,b="");var d=!1;P.forEach(b=>{if(b.msg||b.url)b.msg&&-1==a.search(b.msg)||b.url&&-1==c.search(b.url)||(d=!0)});d||m(f("error","send"),"event","Error",a,c+":"+b,null,{nonInteraction:!0})}},R=()=>{const a=L();!1===r?a.resolve():r.push(a.resolve);
return a.promise()};Registry.register("statistics","7c765150",{init:(a,c,b,d,e)=>{window.onerror=(b,d,e,f,g)=>{let h="";if(g)try{h=g.stack}catch(U){}y(b,c+" "+a+"@"+rea.extension.urls.prepareForReport(d),[e+":"+f,h].join(";"))};document.onsecuritypolicyviolation=b=>{let d="";if(b)try{d=b.stack}catch(O){}y("CSP violation of "+b.effectiveDirective,c+" "+a+"@"+rea.extension.urls.prepareForReport(b.documentURI),[b.sourceFile," -> ",b.lineNumber+":"+b.columnNumber,d].join(";"))};H=!0;e&&(z=e);
d&&(A=d);K(b)},setEnabled:K,isActive:function(a){return l&&!!f(a)},tB:a=>{if(l){var c="";a.updated&&(c="Updated");m(f("browser","send"),"event","Browser",c,navigator.userAgent,null,{nonInteraction:!0})}},tA:(a,c)=>{l&&(c={grant:"Granted",run_at:"RunAt"}[c]||"Used",m(f("api","send"),"event","API",c,a,null,{nonInteraction:!1}))},tC:(a,c,b)=>{if(l){var d="",e="";"init"===c?(e="Initialized",d=a):"error"===c&&(e="Error",d=a+" -> "+b);m(f("cloud","send"),"event","Cloud",e,d,null,{nonInteraction:!1})}},
tS:(a,c,b)=>{if(l){if("i"===b)b="Installed",a+=" <"+(c?c:"?")+">";else if("u"===b){b="Updated";var d=f("script_update","send")}else"b"===b?(b="Blacklisted",a+=" <"+(c?c:"?")+">"):"f"===b?(b="Foisted",a+=" <"+(c?c:"?")+">"):"w"===b?(b="Foisted While Installed",a+=" <"+(c?c:"?")+">"):"m"===b?(b="Revealed",a=c):b="Removed";m(d||f("script","send"),"event","Script",b,a,null,{nonInteraction:!1})}},tE:y,tG:(a,c,b)=>{if(l){var d="",e="";"clicked"===a?(e="Click",d=c+":"+b):"button"===a?(e="Button",d=c):"dialog"===
a&&(e="Dialog");m(f("begging","send"),"event","Begging",e,d,null,{nonInteraction:!1})}}})})(window)});
