'use strict';(()=>{Registry.require(["promise"],()=>{const h=rea.FEATURES,d=Registry.get("promise"),z=[];let l=!0;const u=(()=>{const b=[h.CONSTANTS.STORAGE.VERSION,h.CONSTANTS.STORAGE.TYPE],a={};b.forEach(b=>{a[b]=!0});return{keys:b,has:function(b){return!!a[b]}}})(),n=h.HTML5.LOCALSTORAGE,A=()=>rea.other.openDatabase("tmStorage","1.0","TM Storage",31457280),v=(b,a)=>{if(!b)return a;const c=b[0];b=b.substring(1);switch(c){case "b":return"true"==b;case "n":return Number(b);case "o":try{return JSON.parse(b)}catch(f){console.error("Storage: getValue ERROR: "+
f.message)}return a;default:return b}},w=b=>{const a=(typeof b)[0];switch(a){case "o":try{b=a+JSON.stringify(b)}catch(c){console.error("Storage: setValue ERROR: "+c.message);return}break;default:b=a+b}return b},r=function(b,a){const c=d();var f=Array.prototype.slice.call(arguments,2);let m;"string"==typeof b?b==h.DB.USE&&"clean"==a?console.warn("Storage: can't clean currently active storage"):m=k.implementations[b][a]:m=b[a];if(m)if(f=m.apply(this,f),"object"===typeof f&&f.then)f.then(function(){c.resolve.apply(this,
arguments)},b=>{c.reject()});else return f;else c.resolve();return c.promise()},x=(b,a)=>{const c=d(),f=[];Object.getOwnPropertyNames(a).forEach(c=>{void 0!==a[c]&&f.push(r(b,"setValue",c,a[c]))});d.when(f).done(()=>{c.resolve()});return c.promise()},y=(b,a)=>{const c={};a.forEach(a=>{c[a]=r(b,"getValue",a)});return c};var k={secure:{cookie:(()=>{const b=b=>{document.cookie="s_"+b+"=;expires=Thu, 01 Jan 1970 00:00:00 UTC;path=/"},a=()=>{const b=document.cookie.split(";"),a=[];for(let g=0;g<b.length;g++){var c=
b[g].trim();const q=c.indexOf("=");c=c.substr(0,q);"s_"==c.substr(0,2)&&a.push(c.substr(2))}return a},c={setValue:function(b,a){const c=d();a=w(a);var g=new Date;g.setTime(g.getTime()+47304E7);g="expires="+g.toUTCString();document.cookie="s_"+b+"="+a+";"+g+";path=/";c.resolve();return c.promise()},setValues:function(b){const a=[];Object.keys(b).forEach(f=>{a.push(c.setValue(f,b[f]))});return d.sidebyside(a)},getValue:function(b,a){a:{b="s_"+b+"=";const a=document.cookie.split(";");for(let c=0;c<a.length;c++){let g=
a[c];for(;" "==g.charAt(0);)g=g.substring(1);if(0==g.indexOf(b)){b=g.substring(b.length,g.length);break a}}b=null}return v(b,a)},deleteAll:function(){const a=d();c.listValues().forEach(a=>{b(a)});a.resolve();return a.promise()},deleteValue:function(a){const c=d();b(a);c.resolve();return c.promise()},listValues:function(){return a().map(b=>b)}};return c})()},implementations:{localStorage:(()=>{const b={setValue:function(b,c){const a=d();c=w(c);l&&n.setItem(b,c);a.resolve();return a.promise()},setValues:function(a){const c=
[];Object.keys(a).forEach(d=>{c.push(b.setValue(d,a[d]))});return d.sidebyside(c)},getValue:function(b,c){return v(n.getItem(b,c),c)},deleteAll:function(){const a=d();l&&b.listValues().forEach(b=>{u.has(b)||n.removeItem(b)});a.resolve();return a.promise()},deleteValue:function(b){const a=d();l&&n.removeItem(b);a.resolve();return a.promise()},listValues:function(){const b=[];for(let a=0;a<n.length;a++)b.push(n.key(a));return b}};return{options:{},methods:b}})(),sql:(()=>{let b=null,a=null;const c=
()=>{const b=d();a.db.transaction(c=>{c.executeSql("CREATE TABLE IF NOT EXISTS config(ID INTEGER PRIMARY KEY ASC, name TEXT, value TEXT)",[],b.resolve,a.onError)});return b.promise()},f=()=>{const b=d();a={db:A(),onSuccess:function(b,a){},onError:function(b,a){console.error("webSQL: localDB Error ",a)}};a.db?c().done(b.resolve):(a=null,b.reject());return b.promise()},m={setValue:function(c,g){const q=d(),f=w(g);l&&(b[c]?a.db.transaction(b=>{b.executeSql("UPDATE config SET value=? WHERE name=?",[f,
c],()=>{rea.runtime.lastError&&console.warn(rea.runtime.lastError);q.resolve()},a.onError)}):a.db.transaction(b=>{b.executeSql("INSERT INTO config(name, value) VALUES (?,?)",[c,f],()=>{rea.runtime.lastError&&console.warn(rea.runtime.lastError);q.resolve()},a.onError)}));b[c]=f;l||q.resolve();return q.promise()},setValues:function(b){const a=[];Object.keys(b).forEach(c=>{a.push(m.setValue(c,b[c]))});return d.sidebyside(a)},getValue:function(a,c){return v(b[a],c)},deleteAll:function(){const f=d(),g=
y(m,u.keys);b=g;l?a.db.transaction(b=>{b.executeSql("DROP TABLE config",[],()=>{c().done(()=>{x(m,g).done(f.resolve)})},a.onError)}):f.resolve();return f.promise()},deleteValue:function(c){const g=d();delete b[c];l?a.db.transaction(b=>{b.executeSql("DELETE FROM config WHERE name=?",[c],g.resolve,a.onError)}):g.resolve();return g.promise()},listValues:function(){const a=[];Object.getOwnPropertyNames(b).forEach(b=>{a.push(b)});return a},isWorking:function(){return d.Pledge()}};return{init:function(){const c=
d(),g=(a,e)=>{b={};if(e)for(a=0;a<e.rows.length;a++)b[e.rows.item(a).name]=e.rows.item(a).value;c.resolve()},q=()=>{b?c.resolve():a.db.transaction(b=>{b.executeSql("SELECT * FROM config",[],g,a.onError)})};a?q():f().done(q).fail(c.reject);return c.promise()},clean:function(){b=null;return d.Pledge()},options:{},methods:m}})(),chromeStorage:(()=>{let b=null,a=!1,c=!1;const f=rea.extension.inIncognitoContext?"incognito":"normal",m=(a,d)=>{l&&c&&"local"==d&&a&&Object.keys(a).forEach(c=>{const e=a[c];
e.newValue?e.newValue.origin!==f&&(b[c]=e.newValue.value,k.notifyDifferentOriginChangeListeners(c,e.newValue)):e.oldValue&&e.oldValue.origin!==f&&delete b[c]})},h={setValue:function(a,c){const g=d();b[a]=c;if(l){const b={};b[a]={origin:f,value:c};rea.storage.local.set(b,g.resolve)}else g.resolve();return g.promise()},setValues:function(a){const c=d(),g={};Object.keys(a).forEach(c=>{const e=a[c];b[c]=e;l&&(g[c]={origin:f,value:e})});l?rea.storage.local.set(g,c.resolve):c.resolve();return c.promise()},
getValue:function(a,c){return void 0===b[a]?c:b[a]},deleteAll:function(){const a=d(),c=y(h,u.keys);b=c;l?rea.storage.local.clear(()=>{x(h,c).done(a.resolve)}):a.resolve();return a.promise()},deleteValue:function(a){const c=d();delete b[a];l?rea.storage.local.remove(a,c.resolve):c.resolve();return c.promise()},listValues:function(){const a=[];Object.getOwnPropertyNames(b).forEach(b=>{a.push(b)});return a},setTemporary:function(b){l=!b;c=!0},isSupported:function(){return d.Pledge()},isWorking:function(){const b=
d();let a=0;const c=Date.now(),e={};e.foo=c;const p=c=>{5>=++a?(console.warn("storage:",c?c:"storage set/get test failed!"),window.setTimeout(f,a*a*100)):(console.warn("storage: storage set/get test finally failed!"),t&&(window.clearTimeout(t),t=null,b.reject()))};var t=window.setTimeout(()=>{t=null},18E4),f=()=>{console.log("Storage: test -> start");const a=Date.now();rea.storage.local.set(e,()=>{console.log("Storage: test -> set after "+(Date.now()-a)+"ms");rea.storage.local.get("foo",e=>{console.log("Storage: test -> get after "+
(Date.now()-a)+"ms");if(e){if(e.foo!==c)return p("read value is different "+JSON.stringify(e.foo)+" != "+JSON.stringify(c));if(rea.runtime.lastError)return p(rea.runtime.lastError&&rea.runtime.lastError.message||"lastError is set")}else return p("read value is"+e);rea.storage.local.remove("foo",()=>{console.log("Storage: test -> remove after "+(Date.now()-a)+"ms");t&&(window.clearTimeout(t),t=null,b.resolve())})})})};f();return b.promise()}};return{init:function(){const c=d();b?c.resolve():rea.storage.local.get(null,
d=>{b={};d&&Object.keys(d).forEach(a=>{const c=d[a];b[a]=c&&c.hasOwnProperty("origin")&&c.hasOwnProperty("value")?c.value:c});a||(rea.storage.onChanged.addListener(m),a=!0);c.resolve()});return c.promise()},clean:function(){const a=d();b=null;a.resolve();return a.promise()},options:{},methods:h}})(),file:(()=>{let b=null,a=null;const c=()=>{const b=d(),c=a=>{console.warn("fileStorage: listFiles() error:",a);b.reject()};a.root.getDirectory("data",{create:!0},a=>{const e=a.createReader();let d=[];const p=
()=>{e.readEntries(a=>{a.length?(d=d.concat(a),p()):b.resolve(d)},c)};p()},c);return b.promise()},f=(b,c)=>{const e=d(),p=a=>{console.warn("fileStorage: writeFileData(",b,") error:",a);e.reject()};a.root.getDirectory("data",{create:!0},a=>{a.getFile(b,{create:!0},b=>{b.createWriter(b=>{b.onwriteend=a=>{b.onwriteend=b=>{e.resolve()};b.onerror=p;a=new Blob([c],{type:"text/plain"});b.write(a)};b.truncate(0)},p)},p)},p);return e.promise()},m=b=>{const c=d(),e=a=>{console.warn("fileStorage: getFileData(",
b,") error:",a);c.reject()},f=b=>{const a=new FileReader;a.onloadend=function(){c.resolve(this.result)};a.onerror=e;a.onabort=e;a.readAsText(b)};a.root.getDirectory("data",{create:!0},a=>{a.getFile(b,{},b=>{b.file(b=>{f(b)},e)},e)},e);return c.promise()},h=b=>{const c=d(),e=a=>{console.warn("fileStorage: deleteFile(",b,") error:",a);c.reject()};a.root.getDirectory("data",{create:!0},a=>{a.getFile(b,{create:!1},b=>{b.remove(c.resolve,e)},e)},e);return c.promise()},g=()=>{const b=d(),c=a=>{console.warn("fileStorage: removeDir() error:",
a);b.reject()};a.root.getDirectory("data",{create:!0},a=>{a.removeRecursively(b.resolve,c)},c);return b.promise()},q=()=>{const a=d();b={};const f=[];c().done(c=>{c.forEach(a=>{"string"!==typeof a&&(a=a.name);f.push(m(a).always(c=>{b[a]=c}))});d.when(f).always(()=>{a.resolve()})}).fail(a.resolve);return a.promise()},k={isSupported:function(){const a=d();window.File&&window.FileReader&&window.FileList&&window.Blob?a.resolve():a.reject();return a.promise()},isWorking:function(){return d.Pledge()},setValue:function(a,
c){const e=d();c=w(c);b[a]=c;l?f(a,c).always(e.resolve):e.resolve();return e.promise()},setValues:function(a){const b=[];Object.keys(a).forEach(c=>{b.push(k.setValue(c,a[c]))});return d.sidebyside(b)},getValue:function(a,c){return v(b[a],c)},deleteAll:function(){const a=d(),c=y(k,u.keys);b=c;l?g().always(()=>{x(k,c).always(a.resolve)}):a.resolve();return a.promise()},deleteValue:function(a){const c=d();delete b[a];l?h(a).always(c.resolve):c.resolve();return c.promise()},listValues:function(){const a=
[];Object.getOwnPropertyNames(b).forEach(b=>{a.push(b)});return a}};return{init:()=>{const c=d();b?c.resolve():rea.other.requestFileSystem(window.PERSISTENT,31457280,b=>{a=b;q().done(c.resolve)},a=>{a&&console.warn("fileStorage: ",a);c.reject()});return c.promise()},clean:function(){b=null;return d.Pledge()},options:{},methods:k}})()},migrate:function(b,a,c){const f=d(),m=k.implementations[b],h=k.implementations[a];c=c||{};m&&h?r(b,"init").then(()=>r(a,"init")).then(()=>{const a=d(),b=[];m.methods.listValues().forEach(a=>
{const d=m.methods.getValue(a);c.drop&&b.push(m.methods.deleteValue(a));b.push(h.methods.setValue(a,d))});d.when(b).done(()=>{a.resolve()});return a.promise()}).then(()=>r(a,"clean")).then(()=>r(b,"clean")).done(()=>{f.resolve()}).fail(()=>{f.reject()}):(console.error("Migration: unknown storage implementation(s) ",b,a),f.reject());return f.promise()},isSupported:function(){return d.Pledge()},isWorking:function(){return d.Pledge()},setTemporary:function(b){l=!b},init:function(){console.debug("Storage: use "+
h.DB.USE);Object.getOwnPropertyNames(k.implementations[h.DB.USE].methods).forEach(b=>{Object.defineProperty(k,b,{get:()=>k.implementations[h.DB.USE].methods[b],enumerable:!0})});return k.implementations[h.DB.USE].init?k.implementations[h.DB.USE].init():d.Pledge()},getValues:function(b,a){const c={};a||(a={});Object.getOwnPropertyNames(b).forEach(b=>{c[b]=k.implementations[h.DB.USE].getValue(b,a[b])});return c},factoryReset:function(){n&&n.removeItem(h.CONSTANTS.STORAGE.LEGACY_VERSION);return k.deleteAll()},
isWiped:function(){if("localStorage"===h.DB.USE||!n)return d.Pledge(!1);const b=d(),a=k.getValue(h.CONSTANTS.STORAGE.VERSION);let c=!1;n.getItem(h.CONSTANTS.STORAGE.LEGACY_VERSION)&&!a&&(k.listValues().length?console.warn("storage: unable to find version information"):c=!0);b.resolve(c);return b.promise()},setVersion:function(b,a){const c=d();l?(n&&n.setItem(h.CONSTANTS.STORAGE.LEGACY_VERSION,b),k.setValue(h.CONSTANTS.STORAGE.VERSION,b).then(()=>a?k.setValue(h.CONSTANTS.STORAGE.SCHEMA,a):d.Pledge()).always(c.resolve)):
c.resolve();return c.promise()},getVersion:function(b){const a=d();let c=k.getValue(h.CONSTANTS.STORAGE.VERSION)||k.getValue(h.CONSTANTS.STORAGE.LEGACY_VERSION)||(n?n.getItem(h.CONSTANTS.STORAGE.LEGACY_VERSION):null);c?a.resolve(c):r("sql","init").then(a=>{c=k.implementations.sql.methods.getValue(h.CONSTANTS.STORAGE.LEGACY_VERSION)||b;return r("sql","clean")}).always(()=>{a.resolve(c||b)});return a.promise()},getSchemaVersion:function(){return k.getValue(h.CONSTANTS.STORAGE.SCHEMA,"3.5")},addDifferentOriginChangeListener:function(b,
a){z.push({search:b,cb:a})},notifyDifferentOriginChangeListeners:function(b,a){z.forEach(c=>{0==b.search(c.search)&&c.cb(b,a)})},recover:function(b,a){"string"===typeof b&&(b={method:b,storages:["sql","chromeStorage"]});const c={};b.storages.forEach(a=>{c[a]=!0});if("log"==b.method){let b=null,d,h;const g=[{method:"sql",fn:function(a){console.debug("check sql storage for data...");try{h=A();if(rea.runtime.lastError||!h)return b=rea.runtime.lastError,a();h.transaction(c=>{c.executeSql("CREATE TABLE IF NOT EXISTS config(ID INTEGER PRIMARY KEY ASC, name TEXT, value TEXT)",
[],()=>{console.debug("sql table found/created");a()},(c,d)=>{b=d;a()})})}catch(p){b=p,window.setTimeout(a,1)}}},{method:"sql",fn:function(a){const c={};h.transaction(e=>{e.executeSql("SELECT * FROM config",[],(b,e)=>{if(e)for(b=0;b<e.rows.length;b++)c[e.rows.item(b).name]=e.rows.item(b).value;d=c;window.setTimeout(a,1)},(c,d)=>{b=d;a()})})}},{method:"sql",fn:function(a){const b=d?Object.getOwnPropertyNames(d):[];d&&b.length?(console.debug("found values:"),b.forEach(a=>{console.debug("    ",a,d[a]&&
30<d[a].length?d[a].substr(0,30):d[a])})):(console.warn("no data found"),c.sql=!1);window.setTimeout(a,1)}},{method:"chromeStorage",fn:function(a){console.debug("check chromeStorage for data...");rea.storage.local.get(null,b=>{d=b;a()})}},{method:"chromeStorage",fn:function(a){const b=d?Object.getOwnPropertyNames(d):[];d&&b.length?(console.debug("found values:"),b.forEach(a=>{console.debug("    ",a,d[a]&&30<d[a].length?d[a].substr(0,30):d[a])})):(console.warn("no data found"),c.chromeStorage=!1,window.setTimeout(a,
1))}}];let k=0;const l=()=>{if(b)console.warn("error:",b);else for(;g[k];){if(c[g[k].method]){g[k].fn(l);k++;return}k++}a&&a()};l()}}};Registry.register("storage","7c765150",()=>k)})})();
