'use strict';Registry.require(["helper","convert"],()=>{const n=Registry.get("helper"),l=Registry.get("convert");let p;const A=a=>a&&"http"==a.substr(0,4),E="internal user-agent accept-charset accept-encoding access-control-request-headers access-control-request-method connection content-length cookie cookie2 date dnt expect host keep-alive origin referer te trailer transfer-encoding upgrade via".split(" "),B=a=>E.includes(a)||0===a.indexOf("proxy-")||0===a.indexOf("sec-"),F={"cache-control":"no-cache",
pragma:"no-cache"},G={"cache-control":"max-age=0, must-revalidate"},q=a=>({responseXML:"",responseText:"",response:null,readyState:4,responseHeaders:"",status:0,statusText:"",error:a||"Forbidden"}),v=a=>{if("Blob"===a.type)return new Blob([l.str2arrbuf(a.value)]);if("File"===a.type)return new File([l.str2arrbuf(a.value)],a.name,{type:a.meta,lastModified:a.lastModified||Date.now()});if("FormData"==a.type){const e=new FormData;Object.keys(a.value).forEach(g=>{const b="Array"===a.value[g].type,k=v(a.value[g]),
h=b?k:[k];h.forEach((a,c)=>{e.append(g,h[c])})});return e}if("Array"===a.type||"Object"===a.type){let e,g,b;"Object"===a?(b=Object.keys(a.value),g=a=>a<b.length?b[a]:null,e={}):(g=b=>b<a.value.length?b:null,e=[]);for(let b,h=0;null!==(b=g(h));h++)e[b]=v(a.value[b]);return e}return a.value},r=a=>{const e={};a&&a.split("\n").forEach(a=>{if(a=a.match(/^([^:]+): ?(.*)/)){const b=a[1].toLowerCase();e[b]=(void 0!==e[b]?", ":"")+(a[2]||"").replace(/,/g,"%2C")}});return e},H=a=>{a=a.split(";").filter(a=>
"string"===typeof a&&!!a.trim());var e=a.shift().split("=");const g=e.shift();e=e.join("=");const b={name:g,value:decodeURIComponent(e)};a.forEach(function(a){var e=a.split("=");a=e.shift().trimLeft().toLowerCase();e=e.join("=");"expires"===a?(a=new Date(decodeURIComponent(e)),isNaN(a.getTime())||(b.expires=a)):"max-age"===a?b.maxAge=parseInt(e,10):"secure"===a?b.secure=!0:"httponly"===a?b.httpOnly=!0:"samesite"===a?b.sameSite=e:b[a]=e});return b},I=(a,e,g)=>{void 0===g&&(g={});const b=n.assign({},
e||{}),k=(a,c)=>{if(b[a])b[a]("function"==typeof c?c():c)};e=(a,c)=>{b[a]&&(k(a,c),b[a]=null)};if(g.internal||A(a.url)){var h=window.fetch&&a.url&&"http"==a.url.substr(0,4),l=!p.mozAnon&&a.anonymous,c=a.fetch;return h&&(l||c)?C(a,b,g,e,k):y(a,b,g,e,k)}console.warn("xhr: invalid scheme of url:",a.url);a=q("Invalid scheme");e("onerror",a);e("ondone",a)},z="tm-finalurl"+rea.runtime.short_id.toLowerCase(),D="tm-setcookie"+rea.runtime.short_id.toLowerCase();var C=(a,e,g,b,k)=>{const h=a=>{const c=[];let b,
d;a.headers&&(b=a.headers.get(z)||a.url,a.headers.forEach((a,d)=>{d=d.toLowerCase();[z,D].includes(d)||c.push(d+":"+a)}),(d=a.headers.get(D))&&c.push("set-cookie:"+d));return{readyState:4,responseHeaders:c.join("\n"),finalUrl:b,status:a.status,statusText:a.statusText}},n=c=>{((a,c)=>{const d=[];for(let w=0,b=a.length;w<b;w+=c)d.push(a.slice(w,c+w));return d})(c,parseInt(a.partialSize)).forEach(a=>{k("onpartial",{partial:a})})};try{var c={};c.method=a.method||"GET";c.redirect="follow";if(a.nocache||
a.revalidate)c.cache="no-store";c.credentials=a.anonymous?"omit":"include";if(a.headers){const b={};Object.keys(a.headers).forEach(c=>{let e=c,d=a.headers[c];if(p.prefix)B(c.toLowerCase())&&(e=p.prefix+c,d=null===d?"":l.encodeS(d));else if(null===d)return;b[e]=d});c.headers=new window.Headers(b)}void 0!==a.timeout&&(c.timeout=a.timeout);void 0!==a.data&&(c.body="typified"===a.data_type?v(a.data):"string"===typeof a.data?a.data:JSON.stringify(a.data));var m=window.fetch(a.url,c).then(c=>{const f=h(c);
(0!==f.status||200>f.status||300<=f.status)&&0<a.retries?(a.retries--,C(a,e,g,b,k)):(()=>{let b;if(c.ok)void 0!==a.responseType?(()=>{let d;const b=a.responseType?a.responseType.toLowerCase():"";if(a.convertBinary){if("document"==b)return d=r(f.responseHeaders)["content-type"]||"text/html",new window.Promise(a=>c.text().then(c=>{a({document:c,contentType:d})}));if("json"==b)return c.text();if("arraybuffer"==b||"blob"==b)return c.arrayBuffer().then(a=>l.arrbuf2str(a))}else{if("arraybuffer"==a.responseType)return c.arrayBuffer();
if("blob"==a.responseType)return c.blob();if("document"==a.responseType)return d=r(f.responseHeaders)["content-type"]||"text/xml",(new window.DOMParser).parseFromString(c.text(),d);if("json"==a.responseType)return JSON.parse(c.text());console.warn("xhr: responseType",a.responseType," is not implemented!");return c.text()}})().then(a=>{f.response=a;b()}):c.text().then(a=>{f.response=a;b()});else return f.responseXML=null,f.responseText="",f.response=null,{done:function(a){a()}};return{done:function(a){b=
a}}})().done(()=>{if(a.partialSize&&e.onpartial){const c=a.convertBinary&&f.response?f.response:f.responseText;["response","responseText","responseXML"].forEach(a=>{delete f[a]});c&&(c.length>a.partialSize?n(c):f.response_data=c)}b("onload",f);b("ondone",f)})}).catch(a=>{a=h({status:408,statusText:a.message||"Request Timeout"});b("onerror",a);b("ondone",a)})}catch(t){console.error(t.stack),c=q(t.message),b("onerror",c),b("ondone",c)}return{abort:function(){try{m.abort&&m.abort()}catch(t){}}}},y=(a,
e,g,b,k)=>{let h,x;const c=new XMLHttpRequest(a.anonymous?{mozAnon:!0}:{}),m=d=>{var b="";let e=a.url;if(2<=c.readyState){if(b=c.getAllResponseHeaders())b=b.replace(/tm-finalurl[0-9a-zA-Z]*: .*[\r\n]{1,2}/i,""),b=b.replace(/tm-setcookie[0-9a-zA-Z]*:/i,"set-cookie:");let a;if(a=c.getResponseHeader(z)||c.responseURL)e=a}b={readyState:c.readyState,responseHeaders:b,finalUrl:e,status:2<=c.readyState?c.status:0,statusText:2<=c.readyState?c.statusText:""};d&&4==c.readyState?(c.responseType?(b.responseXML=
null,b.responseText=null,b.responseType=c.responseType):(b.responseXML=c.responseXML,b.responseText=c.responseText),b.response=c.response):(b.responseXML=null,b.responseText="",b.response=null);return b},t=d=>{((a,d)=>{const c=[];for(let b=0,e=a.length;b<e;b+=d)c.push(a.slice(b,d+b));return c})(d,parseInt(a.partialSize)).forEach(a=>{k("onpartial",{partial:a})})},f={onload:function(){const d=m(!0);(0!==d.status||200>d.status||300<=d.status)&&0<a.retries?(a.retries--,y(a,e,g,b,k)):(()=>{if(a.convertBinary&&
d.response){var b=d.responseType?d.responseType.toLowerCase():"";h&&b!==h&&console.warn("xhr: requested responseType "+h+" differs from received "+b);if("document"==b||"document"==h)if("string"==typeof d.response)b=r(d.responseHeaders)["content-type"]||"text/html",d.response={document:d.response,contentType:b};else{b=d.response;const a=b.contentType||"text/html";try{d.response={document:(new XMLSerializer).serializeToString(b.documentElement),contentType:a}}catch(J){const c="unable to serialize content type "+
a;console.warn("xhr: ",c,b);d.response={error:c,contentType:a}}}else if("json"==b)d.response=JSON.stringify(d.response);else{if("blob"==b){let a;const b=new FileReader;b.onload=()=>{d.response=l.arrbuf2str(b.result);a()};b.readAsArrayBuffer(d.response);return{done:function(b){a=b}}}"arraybuffer"==b&&(d.response=l.arrbuf2str(d.response))}}return{done:function(a){a()}}})().done(()=>{if(a.partialSize&&e.onpartial){const b=a.convertBinary&&d.response?d.response:d.responseText;["response","responseText",
"responseXML"].forEach(a=>{delete d[a]});b&&(b.length>a.partialSize?t(b):d.response_data=b)}b("onload",d);4==d.readyState&&b("ondone",d)})},onerror:function(){const c=m();4==c.readyState&&200!=c.status&&0!=c.status&&0<a.retries?(a.retries--,y(a,e,g,b,k)):(b("onerror",c),b("ondone",c))},onloadstart:function(){k("onloadstart",()=>m())},onreadystatechange:function(){k("onreadystatechange",()=>m())},onprogress:function(a){k("onprogress",()=>{const b=m();var d=b;void 0===d&&(d={});try{let e=null,f=null;
if(a.lengthComputable||0<a.total)e=a.loaded,f=a.total;else{const d=!c.responseType||["","text"].includes(c.responseType)?c.responseText:null;let g=Number(r(b.responseHeaders)["content-length"]||"");const h=2<b.readyState&&d?d.length:0;0==g&&(g=-1);e=a.loaded||h;f=a.total||g}d.lengthComputable=a.lengthComputable;d.loaded=e;d.done=e;d.position=e;d.total=f;d.totalSize=f}catch(J){}return d})},ontimeout:function(){const a=m();b("ontimeout");b("ondone",a)},onabort:function(){const a=q("aborted");b("ondone",
a)}};var u=0==Object.keys(f).concat(["ondone"]).filter(a=>!!e[a]).length;if(u)throw Error("Synchronous XHR is not supported anymore");Object.keys(f).forEach(a=>{if(e[a]||["ontimeout","onload","onerror","onabort"].includes(a))c[a]=f[a]});try{if(!g.internal&&!A(a.url))throw Error("Invalid scheme of url: "+a.url);c.open(a.method||"GET",a.url,!u,a.user,a.password);if(a.headers||a.nocache||a.revalidate){const b={};a.headers&&n.assign(b,a.headers);a.nocache?n.assign(b,F):a.revalidate&&n.assign(b,G);Object.keys(b).forEach(a=>
{let d=a,e=b[a];if(p.prefix)B(a.toLowerCase())&&(d=p.prefix+a,e=null===e?"":l.encodeS(e));else if(null===e)return;try{c.setRequestHeader(d,e)}catch(K){console.warn("xhr: rejected header",d,b[a])}})}void 0!==a.overrideMimeType&&c.overrideMimeType(a.overrideMimeType);void 0!==a.responseType&&(h=a.responseType.toLowerCase(),["document","json"].includes(h)||(c.responseType=h));void 0!==a.timeout&&(c.timeout=a.timeout);void 0!==a.data?("typified"===a.data_type?c.send(v(a.data)):"string"===typeof a.data?
c.send(a.data):c.send(JSON.stringify(a.data)),e.onprogress&&c.upload&&(c.upload.onprogress=f.onprogress)):c.send()}catch(d){console.error(d.stack),u=q(d.message),b("onerror",u),b("ondone",u)}x=x||{};return n.copy({abort:function(){c.abort()}},x)};Registry.register("xmlhttprequest","7c765150",()=>({run:I,setConfig:function(a){p=a},getConfig:function(){return p},makeErrorResponse:q,parseCookie:H,parseHeaders:r}))});
